name: chat_box
description: anonymous chat group

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.3.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.5
  crypto: ^3.0.1
  http: ^0.13.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
