name: chat_box
description: anonymous chat group

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  shared_preferences: ^2.0.13
  extended_image: ^6.0.3
  image_picker: ^0.8.5
  crypto: ^3.0.1
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  http: ^0.13.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
